### ISSUE TITLE
Build directory must have a specific location to run the tests

### ISSUE THREAD

**Issue by thelfer** [PaulSt/NGSTrefftz#4]
This issue is created as part of the review of the JOSS paper (openjournals/joss-reviews#4135).

It seems that running the tests requires to build `NGSTrefftz` in a subdirectory of the source directory, as indicated in the `README` file.

Otherwise, this is seems a terrible practice and is probably incompatible with most package manager, hence the issue.

**Comment by PaulSt** [comment]
Thank you very much, this is terrible, yes! Fixed it in 3c2bc6cbba3dcd31226b9fe900963434f070c317
