### ISSUE TITLE
Tests does not work out of the box

### ISSUE THREAD

**Issue by thelfer** [PaulSt/NGSTrefftz#6]
This issue is created as part of the review of the JOSS paper (https://github.com/openjournals/joss-reviews/issues/4135).

The tests do not work out of the box. To run them, I had to:

1. install the package
2. update my environment variables (`PYTHONPATH` in practice)
3. run the tests with `make test`

This is fairly cumbersome and unsual and incompatible with most common practices and package managers.

**Comment by thelfer** [comment]
Note that requiring `ngsolve` to be correctly installed and accessible (thanks to environment variables like `PYTHONPATH` and `LD_LIBRARY_PATH`) is just fine IMHO.

**Comment by PaulSt** [comment]
Fixed with ad9e06a33e4319a9f76250d7c008fd25c5beb8b3
