### ISSUE TITLE
Review of the JOSS paper

### ISSUE THREAD

**Issue by thelfer** [PaulSt/NGSTrefftz#9]
This issue is created as part of the review of the JOSS paper (openjournals/joss-reviews#4135).

My biggest concern with the paper concerns the following statements:

1. line 19: NGSTrefftz provides a framework to implement Trefftz finite element spaces
2. line 40: The aim of this package is to facilitate research into Trefftz methods and to make them more
accessible to a broad audience.

My feeling is that the `NGSTrefftz` currently  does not provide an appealing introduction to the Trefftz method (not in the paper, but on the website and a reference to it in the paper) that would make the reader want to give it a try and maybe contribute to your project. 

I would have expected to find, for example, a introductive text to the method that would be accessible to standard engineer. A minima, a description of the advantages of the Trefftz method (regarding other methods) would help to explain why "research into Trefftz methods" are important.

I have understood that the main drawback of the Trefftz metho is that it requires knowledge of the PDE to solve, but I did not see how I could extend `NGSTrefftz` for my particular PDE (example: linear elasticity or hyperelastictity). Shall I go at the C++ level. Shall I use the "general framework to produce Trefftz spaces implicitly" ?

By that, I do mean that one can not expect the interrested user to go through the provided notebooks (unless you're more than lucky).

**Comment by PaulSt** [comment]
Hi @thelfer,

thank you again for the thorough review. I have updated the website to address these issues.
I put a concise example with convergence plots directly onto the website. Additionally, I put a short text for a starting point into NGSTrefftz. 
The notebooks are a common tool in the NGSolve community. There are still a few options to make the more user friendly to be added in the future. Let me know if this resolves the issue for you for now.

**Comment by thelfer** [comment]
@PaulSt Thanks for your patience. Things are fine for me now. I'll finish my review ASAP.
